/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EditShowDialog.java
 *
 * Created on 10/Nov/2009, 23:35:30
 */

package sted.gui.editshowdialog;

import java.awt.CardLayout;
import sted.datastructures.TVShowEntry;
import sted.gui.StedView;

/**
 *
 * @author tvcsantos
 */
public class EditShowDialog extends javax.swing.JDialog {

    private TVShowEntry entry;
    //private StedView parent = null;

    public EditShowDialog() {
        super();
        initComponents();
        initData();
    }

    /** Creates new form EditShowDialog */
    public EditShowDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initData();        
    }

    public EditShowDialog(StedView parent, boolean modal) {
        super(parent.getFrame(), modal);
        initComponents();
        initData();
    }

    public void initData() {
        if (entry != null) {
            feedsPanel1.setParent(this);
            feedsPanel1.setTVShowEntry(entry);
            filtersPanel1.setParent(this);
            filtersPanel1.setTVShowEntry(entry);
            generalPanel1.setParent(this);
            generalPanel1.setTVShowEntry(entry);
            schedulePanel1.setParent(this);
            schedulePanel1.setTVShowEntry(entry);
        }
        showPanel("card5");
        generalToggleButton.setSelected(true);
    }

    /*public EditShowDialog(StedView view, TVShowEntry entry) {
        super(view.getFrame(), true);
        //parent = view;
        this.entry = entry;
        initComponents();
        showPanel("card5");
        generalToggleButton.setSelected(true);
    }*/

    private void commit() {
        entry.setTitle(generalPanel1.getTitle());
        entry.setSeason(generalPanel1.getSeason());
        entry.setEpisode(generalPanel1.getEpisode());
        entry.setMinSize(filtersPanel1.getMinTorrentSize());
        entry.setMaxSize(filtersPanel1.getMaxTorrentSize());
        entry.setMinSeeders(filtersPanel1.getMinSeedersSize());
        entry.setKeywords(filtersPanel1.getKeywords());
        boolean prevs = entry.isHD();
        boolean news = filtersPanel1.isHD();
        if (prevs != news) {
            entry.setHD(news);
            // TODO update min/max torrent size
        }
        entry.setRSSFeeds(feedsPanel1.getRSSFeeds());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        generalToggleButton = new javax.swing.JToggleButton();
        feedsToggleButton = new javax.swing.JToggleButton();
        filtersToggleButton = new javax.swing.JToggleButton();
        scheduleToggleButton = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        feedsPanel1 = new sted.gui.editshowdialog.FeedsPanel();
        filtersPanel1 = new sted.gui.editshowdialog.FiltersPanel();
        generalPanel1 = new sted.gui.editshowdialog.GeneralPanel();
        schedulePanel1 = new sted.gui.editshowdialog.SchedulePanel();
        helpButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(sted.StedApp.class).getContext().getResourceMap(EditShowDialog.class);
        jToolBar1.setBackground(resourceMap.getColor("jToolBar1.background")); // NOI18N
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setName("jToolBar1"); // NOI18N

        buttonGroup1.add(generalToggleButton);
        generalToggleButton.setIcon(resourceMap.getIcon("generalToggleButton.icon")); // NOI18N
        generalToggleButton.setText(resourceMap.getString("generalToggleButton.text")); // NOI18N
        generalToggleButton.setFocusable(false);
        generalToggleButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        generalToggleButton.setName("generalToggleButton"); // NOI18N
        generalToggleButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        generalToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generalToggleButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(generalToggleButton);

        buttonGroup1.add(feedsToggleButton);
        feedsToggleButton.setIcon(resourceMap.getIcon("feedsToggleButton.icon")); // NOI18N
        feedsToggleButton.setText(resourceMap.getString("feedsToggleButton.text")); // NOI18N
        feedsToggleButton.setFocusable(false);
        feedsToggleButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        feedsToggleButton.setName("feedsToggleButton"); // NOI18N
        feedsToggleButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        feedsToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedsToggleButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(feedsToggleButton);

        buttonGroup1.add(filtersToggleButton);
        filtersToggleButton.setIcon(resourceMap.getIcon("filtersToggleButton.icon")); // NOI18N
        filtersToggleButton.setText(resourceMap.getString("filtersToggleButton.text")); // NOI18N
        filtersToggleButton.setFocusable(false);
        filtersToggleButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        filtersToggleButton.setName("filtersToggleButton"); // NOI18N
        filtersToggleButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        filtersToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtersToggleButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(filtersToggleButton);

        buttonGroup1.add(scheduleToggleButton);
        scheduleToggleButton.setIcon(resourceMap.getIcon("scheduleToggleButton.icon")); // NOI18N
        scheduleToggleButton.setText(resourceMap.getString("scheduleToggleButton.text")); // NOI18N
        scheduleToggleButton.setFocusable(false);
        scheduleToggleButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        scheduleToggleButton.setName("scheduleToggleButton"); // NOI18N
        scheduleToggleButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        scheduleToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleToggleButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(scheduleToggleButton);

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.CardLayout());

        feedsPanel1.setName("feedsPanel1"); // NOI18N
        jPanel1.add(feedsPanel1, "card2");

        filtersPanel1.setName("filtersPanel1"); // NOI18N
        jPanel1.add(filtersPanel1, "card3");

        generalPanel1.setName("generalPanel1"); // NOI18N
        jPanel1.add(generalPanel1, "card4");

        schedulePanel1.setName("schedulePanel1"); // NOI18N
        jPanel1.add(schedulePanel1, "card5");

        helpButton.setIcon(resourceMap.getIcon("helpButton.icon")); // NOI18N
        helpButton.setText(resourceMap.getString("helpButton.text")); // NOI18N
        helpButton.setName("helpButton"); // NOI18N

        cancelButton.setText(resourceMap.getString("cancelButton.text")); // NOI18N
        cancelButton.setName("cancelButton"); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        saveButton.setText(resourceMap.getString("saveButton.text")); // NOI18N
        saveButton.setName("saveButton"); // NOI18N
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(helpButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 299, Short.MAX_VALUE)
                .addComponent(saveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(helpButton)
                    .addComponent(cancelButton)
                    .addComponent(saveButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generalToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generalToggleButtonActionPerformed
        showPanel("card5");
    }//GEN-LAST:event_generalToggleButtonActionPerformed

    private void feedsToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedsToggleButtonActionPerformed
        showPanel("card2");
    }//GEN-LAST:event_feedsToggleButtonActionPerformed

    private void filtersToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtersToggleButtonActionPerformed
        showPanel("card3");
    }//GEN-LAST:event_filtersToggleButtonActionPerformed

    private void scheduleToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleToggleButtonActionPerformed
        showPanel("card4");
    }//GEN-LAST:event_scheduleToggleButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        commit();
        dispose();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelButton;
    private sted.gui.editshowdialog.FeedsPanel feedsPanel1;
    private javax.swing.JToggleButton feedsToggleButton;
    private sted.gui.editshowdialog.FiltersPanel filtersPanel1;
    private javax.swing.JToggleButton filtersToggleButton;
    private sted.gui.editshowdialog.GeneralPanel generalPanel1;
    private javax.swing.JToggleButton generalToggleButton;
    private javax.swing.JButton helpButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton saveButton;
    private sted.gui.editshowdialog.SchedulePanel schedulePanel1;
    private javax.swing.JToggleButton scheduleToggleButton;
    // End of variables declaration//GEN-END:variables


    private void showPanel(String command) {
        CardLayout cl = (CardLayout) (jPanel1.getLayout());
        cl.show(jPanel1, command);
        //this.currentTab = command;
    }

    public void setEntry(TVShowEntry entry) {
        this.entry = entry;
        initData();
    }
}
